// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

/* reloadしないと表示されない（MVP後確認）
import AddToAnyController from "./add_to_any_controller"
application.register("add-to-any", AddToAnyController)
*/