version: '3'
services:
  db:
    image: postgres
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  rails:
    build:
        context: .
        dockerfile: Dockerfile.dev
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      - RAILS_DATABASE_HOST=db
    volumes:
      - .:/myapp
volumes:
  pgdata: