version: '3'
services:
  db:
    image: postgres
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  rails:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/myapp
volumes:
  pgdata: