# fly.toml app configuration file generated for web-app-1-solitary-bird-4473 on 2024-04-08T14:40:46+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'web-app-1-solitary-bird-4473'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
