# fly.toml app configuration file generated for web-app-1 on 2024-04-10T16:50:14+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'web-app-1'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
